# OpenAI Corpus Re-embedding Configuration
# This file contains configurable parameters for the re-embedding process

# Embedding Provider Configuration
embedding:
  provider: "openai"
  model: "text-embedding-3-small"
  dimensions: 1536  # Match expected default for compatibility
  batch_size: 128

# Content Filtering
filtering:
  # Skip runs with these exact characteristics (empty templates)
  skip_templates:
    - title: "Overview"
      text_length: 114
      description: "Personal site empty template"
    - title: "Descripción general"
      text_length: 172
      description: "Spanish site empty template"

  # Minimum document count to consider a run worth embedding
  min_docs: 1

  # Sort runs by document count (largest first for efficiency)
  sort_by_size: true

# Processing Configuration
processing:
  # Maximum concurrent runs (currently 1 for serial processing)
  max_concurrent: 1

  # Retry failed runs
  retry_failed: true
  max_retries: 3

  # Continue on errors (don't stop the entire process)
  continue_on_error: true

# Logging and Monitoring
logging:
  log_dir: "var/logs"
  progress_file: "var/reembed_progress.json"
  error_log: "var/reembed_errors.log"
  cost_log: "var/reembed_cost.log"

  # Log level: debug, info, warn, error
  level: "info"

# Cost Estimation
cost_estimation:
  # Tokens per character (rough estimate)
  tokens_per_char: 4

  # Cost per 1K tokens for text-embedding-3-small
  cost_per_1k_tokens: 0.0001

  # Enable cost tracking
  enabled: true

# Resume and Recovery
recovery:
  # Resume from previous run if progress file exists
  resume_enabled: true

  # Skip already completed runs
  skip_completed: true

  # Backup progress file before starting
  backup_progress: true
